apiVersion: v1
kind: ConfigMap
metadata:
  name: node0-config
  namespace: cantian
data:
  deploy_param.json: |
    {
      "upgrade_mode": "rollup",
      "deploy_mode": "combined",
      "deploy_user": "ctdba:ctdba",
      "cluster_id": "0",
      "cluster_name": "cluster1234567",
      "remote_cluster_name": "cluster1234567",
      "node_id": "0",
      "cantian_vlan_ip": "net1;net2",
      "storage_vlan_ip": "66.66.66.10;66.66.66.11;77.77.77.10;77.77.77.11",
      "cms_ip": "cantian-node0.cantian-svc.cantian.svc.cluster.local;cantian-node1.cantian-svc.cantian.svc.cluster.local",
      "storage_dbstore_fs": "foo",
      "storage_dbstore_page_fs": "foo_page",
      "storage_share_fs": "share",
      "storage_archive_fs": "archive",
      "storage_metadata_fs": "metadata",
      "dbstore_fs_vstore_id": "0",
      "cantian_in_container": "1",
      "mysql_in_container": "1",
      "vstore_id": "0",
      "share_logic_ip": "55.55.55.102",
      "archive_logic_ip": "55.55.55.102",
      "metadata_logic_ip": "55.55.55.102",
      "mes_type": "UC",
      "mes_ssl_switch": false,
      "link_type": "1",
      "db_type": "1",
      "deploy_policy": "default",
      "kerberos_key": "sys",
      "mysql_metadata_in_cantian": true,
      "MAX_ARCH_FILES_SIZE": "300G",
      "ca_path": "/opt/certificate/ca.crt",
      "crt_path": "/opt/certificate/mes.crt",
      "key_path": "/opt/certificate/mes.key",
      "dr_deploy": {
        "active": {
          "dm_ip": "",
          "dm_user": "",
          "esn": ""
        },
        "standby": {
          "dm_ip": "",
          "dm_user": "",
          "esn": "",
          "pool_id": "",
          "dbstore_fs_vstore_id": ""
        }
      }
    }
  mysql_config.json: |
    {
      "read_rnd_buffer_size": "1M",
      "skip-ssl": true
    }
  mem_spec: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node1-config
  namespace: cantian
data:
  deploy_param.json: |
    {
      "upgrade_mode": "rollup",
      "deploy_mode": "combined",
      "deploy_user": "ctdba:ctdba",
      "cluster_id": "0",
      "cluster_name": "cluster1234567",
      "remote_cluster_name": "cluster1234567",
      "node_id": "1",
      "cantian_vlan_ip": "net1;net2",
      "storage_vlan_ip": "66.66.66.10;66.66.66.11;77.77.77.10;77.77.77.11",
      "cms_ip": "cantian-node0.cantian-svc.cantian.svc.cluster.local;cantian-node1.cantian-svc.cantian.svc.cluster.local",
      "storage_dbstore_fs": "foo",
      "storage_dbstore_page_fs": "foo_page",
      "storage_share_fs": "share",
      "storage_archive_fs": "archive",
      "storage_metadata_fs": "metadata",
      "dbstore_fs_vstore_id": "0",
      "cantian_in_container": "1",
      "mysql_in_container": "1",
      "vstore_id": "0",
      "share_logic_ip": "55.55.55.102",
      "archive_logic_ip": "55.55.55.102",
      "metadata_logic_ip": "55.55.55.102",
      "mes_type": "UC",
      "mes_ssl_switch": false,
      "link_type": "1",
      "db_type": "1",
      "deploy_policy": "default",
      "kerberos_key": "sys",
      "mysql_metadata_in_cantian": true,
      "MAX_ARCH_FILES_SIZE": "300G",
      "ca_path": "/opt/certificate/ca.crt",
      "crt_path": "/opt/certificate/mes.crt",
      "key_path": "/opt/certificate/mes.key",
      "dr_deploy": {
        "active": {
          "dm_ip": "",
          "dm_user": "",
          "esn": ""
        },
        "standby": {
          "dm_ip": "",
          "dm_user": "",
          "esn": "",
          "pool_id": "",
          "dbstore_fs_vstore_id": ""
        }
      }
    }
  mysql_config.json: |
    {
      "read_rnd_buffer_size": "1M",
      "skip-ssl": true
    }
  mem_spec: "1"
#   内存：60G mem_spec -> "1"
#  "SESSIONS": "1024",
#  "TEMP_BUFFER_SIZE": "256M",
#  "LARGE_POOL_SIZE": "256M",
#  "DATA_BUFFER_SIZE": "30G",
#  "SHARED_POOL_SIZE": "512M",
#  "DTC_RCY_PARAL_BUF_LIST_SIZE": "8",
#  "SHM_MEMORY_REDUCTION_RATIO": "8"

#   内存：60G mem_spec -> "2"
#  "SESSIONS": "2048",
#  "TEMP_BUFFER_SIZE": "512M",
#  "LARGE_POOL_SIZE": "512M",
#  "DATA_BUFFER_SIZE": "60G",
#  "SHARED_POOL_SIZE": "1G",
#  "DTC_RCY_PARAL_BUF_LIST_SIZE": "16",
#  "SHM_MEMORY_REDUCTION_RATIO": "4"

#   内存：60G mem_spec -> "2"
#  "SESSIONS": "4096",
#  "TEMP_BUFFER_SIZE": "1G",
#  "LARGE_POOL_SIZE": "1G",
#  "DATA_BUFFER_SIZE": "120G",
#  "SHARED_POOL_SIZE": "2G",
#  "DTC_RCY_PARAL_BUF_LIST_SIZE": "32",
#  "SHM_MEMORY_REDUCTION_RATIO": "2"
